### ISSUE TITLE
Syntax hightlighter is too slow on uBO filters

### ISSUE THREAD

**Issue by ameshkov** [ameshkov/VscodeAdblockSyntax#17]
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

**Comment by yourduskquibbles** [comment]
@ameshkov Just searched around because I ran into this problem myself and found this issue. 

Any idea what causes this behavior? I originally thought it may be because of the 20,000+ character count `##+js(bab-defuser.js)` filter but tried splitting it up in a separate test file into filter segments with less domains but it still crashes my VS Code when I have 5+ 4,000 character count `##+js(bab-defuser.js)` filters so guessing that probably isn't the cause of the issue.

**Comment by ameshkov** [comment]
It seems that the issue went away in v0.0.14: https://github.com/ameshkov/VscodeAdblockSyntax/releases/tag/v0.0.14

I am not sure what was the issue, though :)

**Comment by yourduskquibbles** [comment]
It also appears fixed for me to with latest version. Thanks!
